name: GitHub Readme YouTube Cards
on:
  schedule:
    # Runs every hour, on the hour
    - cron: "0 * * * *"
  workflow_dispatch:
permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Generate YouTube cards
        uses: DenverCoder1/github-readme-youtube-cards@main
        with:
          channel_id: UCLfy2P0XPuzeEKi0J4dWKxw
          readme_path: README.md   # path to update
          comment_tag_name: YOUTUBE-CARDS
          max_videos: 6

      - name: Commit and push if changed
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Update YouTube cards"
             
